# Generated by Django 5.2.4 on 2025-07-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
